POST http://localhost:4000/ads
Content-Type: application/json

{
  "title": "robinmobile",
  "description": "lorem ipsum",
  "owner": "a@a.com",
  "price": 500,
  "picture": "",
  "location": "Paris",
  "category": 3,
  "tags": [4,6]
}